// controllers/aiSearchController.js
const crypto = require("crypto");
const Product = require("../model/Product");
const redis = require("../config/redis");
const { runSearchAgent, generateFinalResponse } = require("../services/aiSearchService");
const rankResults = require("../Utils/rankResults");

const aiSearch = async (req, res) => {
  const { query } = req.body;
  const campus = req.query.campus || null;
  console.log(req.body)

  if (!query || typeof query !== "string" || query.trim().length < 3) {
    return res.status(400).json({ success: false, message: "Please enter a valid search query." });
  }

  const cacheKey = `ai_agent_search:${crypto
    .createHash("md5")
    .update(`${query.trim().toLowerCase()}|${campus || ""}`)
    .digest("hex")}`;

  try {
    // 1. Cache Check
    const cached = await redis.get(cacheKey);
    if (cached) return res.status(200).json(JSON.parse(cached));

    // 2. Start the Agent Turn
    const agentResponse = await runSearchAgent(query, campus);

    // Check if Gemini invoked our database search tool
    if (agentResponse.functionCalls && agentResponse.functionCalls.length > 0) {
      const toolCall = agentResponse.functionCalls[0];
      const args = toolCall.args; // Parameters generated by Gemini

      // 3. Construct your Mongoose filter
      let filter = { isAvailable: true }; // Only fetch available items
      console.log("Gemini parsed arguments:", args);
      
      if (args.searchTerm) {
        filter.$text = { $search: args.searchTerm };
      }
      if (args.category && args.category !== "none") {
        filter.category = args.category;
      }
      
      // ======================================================
      // FIX 1: ADD STRICT SUBCATEGORY FILTER
      // ======================================================
      if (args.subcategory && args.subcategory !== "none") {
        filter.subcategory = args.subcategory;
      }
      
      if (campus) filter.campus = campus;

      // Price limits mapping
      if (args.priceMax || args.priceMin) {
        filter.price = {};
        if (args.priceMax) filter.price.$lte = args.priceMax;
        if (args.priceMin) filter.price.$gte = args.priceMin;
      }

      // Query execution
      let products = await Product.find(filter).limit(30).lean();

      // Relax text search fallback if matching strictly by keywords yields empty rows
      if (products.length === 0 && filter.$text) {
        const { $text, ...relaxedFilter } = filter;
        products = await Product.find(relaxedFilter).limit(30).lean();
      }

      // ======================================================
      // FIX 2: ALIGN ARGUMENTS WITH RANKING FUNCTION EXPECTATIONS
      // ======================================================
      // Our ranking function expects 'query' inside the intent object
      const rankingIntent = {
        ...args,
        query: args.searchTerm || query // Use AI-optimized search term, fallback to original query
      };

      const rankedMatches = rankResults(products, rankingIntent).slice(0, 10);

      // Clean payload metadata to feed Gemini context without blowing token caps
      const minimizedDbResult = rankedMatches.map(p => ({
        id: p._id,
        name: p.name,
        price: `GHS ${p.price}`,
        condition: p.condition,
        campus: p.campus
      }));

      // 4. Send the factual rows back to Gemini to synthesize a natural chat response
      const cleverSummary = await generateFinalResponse(query, agentResponse, minimizedDbResult);

      const payload = {
        success: true,
        query,
        aiResponse: cleverSummary, 
        count: rankedMatches.length,
        results: rankedMatches,     // Pure, correctly categorized, and ranked items
      };

      await redis.set(cacheKey, JSON.stringify(payload), "EX", 600);
      return res.status(200).json(payload);
    }

    // Fallback if Gemini directly answers without invoking the tool
    return res.status(200).json({
      success: true,
      query,
      aiResponse: agentResponse.text,
      count: 0,
      results: []
    });

  } catch (err) {
    console.error("Agent Search Error:", err);
    return res.status(500).json({
      success: false,
      message: "Search is temporarily down—try browsing categories!",
    });
  }
};

module.exports = { aiSearch };